### ISSUE TITLE
Fall 2018: Generalization Games Roadmap

### ISSUE THREAD

**Issue by schopra8** [mhtess/gen-games#48]
Stage 0 (Documentation):
- [x] **Completed 10/2/2018:** Clean File Structure
- ~~Organize Data (Data was collected with cosub as well it’s predecessor, consolidate into the cosub data format). Organize all data in same structure and format.~~ 
- [x]  **Completed 11/10/2018:** Add better documentation as to which game corresponds to which data
- [x] **Completed 10/2/2018:** Remove unnecessary/failed experiments from the repo (where the server game setup failed). It adds clutter and makes things confusing.
- [ ] Make sure that there aren’t any changes to shared code files across the game.
- [x] **Completed 10/2/2018:** Anonymize data and push collected data to repo. 
- [ ] Merge this branch into master — it’s getting huge and a bit unruly. Should make smaller branches from this point forward.

Stage 1 (Future Experiment Infra):

- [ ] Verify each games till works as desired. Code hasn’t changed since running the experiments but you never know.
- [ ] Add instructions as how to run experiments, pull data from Mturk, run automated cleaning process.

Stage 2 (Summarization Task):
- [X]  Finish coding summarization task.
- [X]  Determine stimuli for summarization task, probably same from original pilot.
- [X]  Run experiment in sandbox.
- [X]  Run experiment in production.
- [X] Compare results to those of original task. Is it cheaper and similarly accurate to gather data this way?

Stage 3 (Experimental Design & Iteration):
- [X] Think about the point we are trying to convey with learning times. How to tweak experiment, without 30-second penalty?
- [X] Brainstorm list of interesting concepts.
- [ ]  Read up about Information Integration Categories.
- [ ] Pilot new concepts + Information Integration Categories in experiment.
- [ ] Pilot 1-player version of game with text saved and uploaded to another half of the game that is 1-player, where second player reads text, rather than engage in text chat.

Stage 4 (Modeling):
- [ ] Does rational rules predict results? Where does it work? Where does it fail?
- [ ] What are alternatives to rational rules models?

**Comment by schopra8** [comment]
**Update: 10/9/2018** -- Removed **Organize Data** goal from Stage 0. The only data with subiterator is the validation experiment for single player concept rules, i.e. game-5, and the pilot of mp-game-3. At the moment it doesn't seem like a great use of time to consolidate the data into the same format; since we are not using those for current analyses. Rather, we can just parse this small set of data in a different way -- as we already do in our R Markdown notebooks.

**Comment by schopra8** [comment]
**Update: 10/9/2018** Expunged old data from git repository, fixed + generalized the data cleaning & anonymization script for multiplayer games collected with cosub, and added new, cleaned data to repository under `data` folder to maintain separation between mturk collected data (maintained only locally) and anonymized data for analysis and distribution.

**Comment by schopra8** [comment]
Marking this as closed, since we are moving from on this piloting goals.
